### ISSUE TITLE
Update monitoring configuration to track Render deployment instead of local service

### ISSUE THREAD

**Issue by eliorabaev** [eliorabaev/DevopsFinal#34]
## **Issue Summary**
Our current monitoring infrastructure is configured for local development where all services run in Docker Compose. However, our production URL shortener API is deployed on Render at `https://url-shortener-latest-gccb.onrender.com`. We need to reconfigure our monitoring stack to create a **hybrid architecture** where:
- **API Service**: Runs on Render (production)
- **Monitoring Stack**: Runs locally via Docker Compose (Prometheus, Grafana, Node Exporter)

This approach allows us to maintain comprehensive monitoring of our production service while keeping monitoring infrastructure under our direct control.

### **Architecture Mismatch**
Our `docker-compose.yml` currently defines a `url-shortener` service that:
1. **Conflicts** with the actual production deployment on Render
2. **Wastes resources** by running an unused local API instance
3. **Creates confusion** about which service is being monitored
4. **Prevents proper monitoring** of the actual production service

### **Monitoring Gaps**
- Prometheus is scraping `url-shortener:8000` (non-existent local service)
- Grafana dashboards show no data or stale local data
- Alerts cannot fire for real production issues
- No visibility into actual user traffic and performance

### **DevOps Best Practices**
This change aligns with modern DevOps practices:
- **Separation of Concerns**: Production API vs. monitoring infrastructure
- **Cost Optimization**: Use free Render tier for API, local resources for monitoring
- **Hybrid Cloud**: Combining cloud services with local tooling
- **Real Production Monitoring**: Track actual user-facing service

### 1. **docker-compose.yml** - Remove Local API Service

**Current Issue:**
```yaml
services:
  url-shortener:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    # ... this service shouldn't exist
```

**Required Changes:**
- [ ] **Remove entire `url-shortener` service block** - this prevents port conflicts and resource waste
- [ ] **Update Prometheus dependency** - remove `url-shortener` from `depends_on` array
- [ ] **Clean up network references** - ensure monitoring network only includes necessary services
- [ ] **Update service labels** - remove any labels referencing the local url-shortener

**Expected Result:** Docker Compose will start only infrastructure services (Prometheus, Grafana, Node Exporter)

### 2. **monitoring/prometheus/prometheus.yml** - External Service Scraping

**Current Configuration:**
```yaml
- job_name: 'url-shortener'
  static_configs:
    - targets: ['url-shortener:8000']  # ❌ Internal Docker service
  scrape_interval: 5s                 # ❌ Too frequent for external service
  scrape_timeout: 5s
  metrics_path: '/metrics'
```

**Required Updates:**
- [ ] **Update target URL:**
  ```yaml
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['url-shortener-latest-gccb.onrender.com:443']
    scheme: https  # ✅ Required for Render HTTPS
    scrape_interval: 30s  # ✅ Appropriate for external service
    scrape_timeout: 15s   # ✅ Allow time for network latency
    metrics_path: '/metrics'
  ```

- [ ] **Update relabel configs:**
  ```yaml
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
      replacement: 'url-shortener-render-prod'  # ✅ Clear instance identification
    - target_label: service
      replacement: 'url-shortener'
    - target_label: environment
      replacement: 'production'  # ✅ Add environment label
    - target_label: deployment_type
      replacement: 'render'      # ✅ Add deployment type
  ```

**Technical Considerations:**
- **HTTPS Requirement**: Render serves over HTTPS, requires `scheme: https`
- **Network Latency**: External scraping needs longer timeouts
- **Rate Limiting**: Render may throttle frequent requests
- **Service Discovery**: Static config appropriate for single Render app

### 3. **monitoring/prometheus/alerts.yml** - Production-Aware Alerting

**Current Issues:**
- Alert thresholds may be inappropriate for production workload
- Instance labels reference local Docker containers
- Alert descriptions don't reflect external deployment

**Required Updates:**

- [ ] **Update service identification in alerts:**
  ```yaml
  # Before:
  expr: up{job="url-shortener", instance="url-shortener-app"} == 0
  
  # After:
  expr: up{job="url-shortener"} == 0  # Don't hardcode instance
  ```

- [ ] **Enhance alert annotations for Render context:**
  ```yaml
  annotations:
    summary: "URL Shortener service is DOWN on Render"
    description: |
      The URL shortener service deployed on Render has been unavailable for more than 1 minute.
      Service URL: https://url-shortener-latest-gccb.onrender.com
      Instance: {{ $labels.instance }}
      Environment: {{ $labels.environment }}
      This affects all production users!
    dashboard_url: "http://localhost:3000/d/url-shortener"
    render_dashboard: "https://dashboard.render.com"  # ✅ Add Render dashboard link
  ```

- [ ] **Adjust thresholds for external monitoring:**
  ```yaml
  # Consider Render-specific characteristics:
  - alert: URLShortenerSlowResponse
    expr: histogram_quantile(0.95, rate(request_duration_seconds_bucket{job="url-shortener"}[5m])) > 2  # Increased from 1s
    for: 5m  # Longer duration to account for cold starts
  ```

- [ ] **Add Render-specific alerts:**
  ```yaml
  - alert: RenderServiceColdStart
    expr: increase(urls_created_total[2m]) == 0 AND increase(urls_created_total[30m]) > 0
    for: 0m
    labels:
      severity: info
    annotations:
      summary: "Service may be experiencing cold start on Render"
  ```

### 4. **monitoring/grafana/dashboards/url-shortener-dashboard.json** - Production Dashboard

**Required Updates:**
- [ ] **Update dashboard title and description:**
  ```json
  "title": "URL Shortener - Production Monitoring (Render Deployment)"
  "description": "Monitoring dashboard for URL shortener service running on Render"
  ```

- [ ] **Review and update Prometheus queries:**
  - Remove any hardcoded `instance` filters
  - Ensure queries work with new label structure
  - Add environment/deployment_type filters where appropriate

- [ ] **Add Render-specific panels:**
  - Service uptime with cold start indicators
  - Request patterns showing Render sleep/wake cycles
  - External monitoring health checks

- [ ] **Update variable definitions:**
  - If dashboard uses variables for instance selection
  - Update to work with new instance naming scheme

### **Network Architecture Changes**

**Before (All Local):**
```
┌─────────────────┐    ┌──────────────┐    ┌─────────────┐
│   Prometheus    │───▶│ url-shortener│───▶│   Grafana   │
│  (localhost)    │    │ (localhost)  │    │ (localhost) │
└─────────────────┘    └──────────────┘    └─────────────┘
```

**After (Hybrid):**
```
┌─────────────────┐    ┌──────────────┐    ┌─────────────┐
│   Prometheus    │───▶│ url-shortener│───▶│   Grafana   │
│  (localhost)    │    │   (Render)   │    │ (localhost) │
└─────────────────┘    └──────────────┘    └─────────────┘
```

### **External Service Monitoring Considerations**

**HTTPS and SSL/TLS:**
- Render provides valid SSL certificates
- Prometheus handles HTTPS automatically with `scheme: https`
- No custom TLS configuration required

**Network Connectivity:**
- Prometheus makes outbound HTTPS requests to Render
- No firewall changes needed on local machine
- Render accepts incoming requests on port 443

**Service Discovery:**
- Static configuration appropriate for single Render service
- Consider dynamic discovery if multiple services deployed
- Future enhancement: Render API integration for auto-discovery

**Rate Limiting and Performance:**
- Render free tier has bandwidth limitations
- 30-second scrape interval balances data freshness with resource usage
- Monitor Render metrics to avoid hitting limits

### **Render Platform Specifics**

**Free Tier Limitations:**
- Services sleep after 30 minutes of inactivity
- Cold start time: 10-30 seconds
- Monitoring should account for these patterns

**Uptime Patterns:**
- Expect periodic downtime during sleep periods
- Configure alerts to avoid false positives during expected downtime
- Consider implementing wake-up requests if needed

**Resource Monitoring:**
- Render provides built-in metrics via dashboard
- Our Prometheus setup captures application-level metrics
- Combine both for comprehensive monitoring

### **Pre-Implementation Testing**
- [ ] **Verify Render service accessibility:**
  ```bash
  curl -I https://url-shortener-latest-gccb.onrender.com/metrics
  # Expected: 200 OK with Content-Type: text/plain
  ```

- [ ] **Test HTTPS connectivity:**
  ```bash
  openssl s_client -connect url-shortener-latest-gccb.onrender.com:443
  # Expected: Valid SSL certificate information
  ```

### **Implementation Testing**
- [ ] **Docker Compose validation:**
  ```bash
  docker-compose config  # Validate YAML syntax
  docker-compose up -d   # Start only monitoring services
  docker-compose ps      # Verify only 3 services running
  ```

- [ ] **Prometheus target verification:**
  ```bash
  # Check targets page
  curl -s http://localhost:9090/api/v1/targets | jq '.data.activeTargets[] | select(.job=="url-shortener")'
  # Expected: Target with "up" health status
  ```

- [ ] **Metrics data validation:**
  ```bash
  # Query for URL shortener metrics
  curl -s 'http://localhost:9090/api/v1/query?query=urls_created_total'
  # Expected: Valid metric data from Render service
  ```

### **End-to-End Testing**
- [ ] **Grafana dashboard functionality:**
  - All panels load without errors
  - Data appears within 1-2 minutes
  - Time series show recent data points
  - No "No data" errors in panels

- [ ] **Alert system validation:**
  ```bash
  # Temporarily stop Render service or block network
  # Verify alerts fire within expected timeframes
  # Confirm alert notifications contain correct information
  ```

- [ ] **Production workflow testing:**
  ```bash
  # Create short URL via Render API
  curl -X POST "https://url-shortener-latest-gccb.onrender.com/shorten" \
       -H "Content-Type: application/json" \
       -d '{"url": "https://example.com"}'
  
  # Verify metrics reflect the operation
  # Check Grafana dashboards update
  ```

### **Issue: CORS Restrictions**
**Symptom:** Prometheus fails to scrape metrics with 403/CORS errors
**Solution:** 
```python
# Add to app/main.py if needed
from fastapi.middleware.cors import CORSMiddleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Or restrict to monitoring IP
    allow_methods=["GET"],
    allow_headers=["*"],
)
```

### **Issue: Render Service Sleeping**
**Symptom:** Intermittent monitoring gaps, "service down" alerts
**Mitigation:**
- Implement wake-up requests every 25 minutes
- Adjust alert thresholds to account for cold starts
- Consider upgrading to Render paid tier for always-on service

### **Issue: Network Timeouts**
**Symptom:** Prometheus scrape failures, timeout errors
**Solution:**
- Increase `scrape_timeout` to 20-30 seconds
- Reduce `scrape_interval` frequency if needed
- Monitor network latency between local machine and Render

### **Issue: Rate Limiting**
**Symptom:** HTTP 429 responses from Render
**Solution:**
- Increase scrape interval to reduce request frequency
- Monitor Render bandwidth usage
- Consider caching strategies for metrics

### **Functional Requirements**
1. **✅ Service Isolation:** `docker-compose up -d` starts exactly 3 services (Prometheus, Grafana, Node Exporter)
2. **✅ External Monitoring:** Prometheus successfully scrapes metrics from `https://url-shortener-latest-gccb.onrender.com/metrics`
3. **✅ Data Flow:** Grafana dashboards display real-time metrics from production Render deployment
4. **✅ Alert System:** All alerts work correctly with external service monitoring
5. **✅ Documentation:** README accurately reflects hybrid deployment architecture

### **Performance Requirements**
1. **✅ Scrape Success Rate:** >95% successful metric scrapes over 24-hour period
2. **✅ Dashboard Load Time:** Grafana panels load within 10 seconds
3. **✅ Alert Latency:** Critical alerts fire within 2 minutes of condition
4. **✅ Data Retention:** Metrics history preserved during transition

### **Operational Requirements**
1. **✅ Zero Downtime:** Changes implemented without service interruption
2. **✅ Rollback Plan:** Can revert to previous configuration if needed
3. **✅ Monitoring Coverage:** No gaps in monitoring during transition
4. **✅ Documentation:** Updated documentation and runbooks

### **Service URLs**
- **Production API:** https://url-shortener-latest-gccb.onrender.com
- **API Documentation:** https://url-shortener-latest-gccb.onrender.com/docs
- **Metrics Endpoint:** https://url-shortener-latest-gccb.onrender.com/metrics
- **Local Prometheus:** http://localhost:9090
- **Local Grafana:** http://localhost:3000

### **Configuration Files to Modify**
- `docker-compose.yml` (remove url-shortener service)
- `monitoring/prometheus/prometheus.yml` (update scrape targets)
- `monitoring/prometheus/alerts.yml` (update alert rules)
- `monitoring/grafana/dashboards/url-shortener-dashboard.json` (update queries)

### **External Dependencies**
- Render platform availability
- HTTPS/SSL certificate validity
- Network connectivity to Render services
- Render free tier limitations and quotas
